# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hnd/ext.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hnd/ext.proto',
  package='hnd',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rhnd/ext.proto\x12\x03hnd\x1a google/protobuf/descriptor.proto\"7\n\x11HttpServerOptions\x12\x14\n\x0cisHttpServer\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\"-\n\x0fHttpStatusError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\"|\n\x0bHttpOptions\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0c\n\x04impl\x18\x03 \x01(\t\x12-\n\x0f\x65rror_overrides\x18\x04 \x03(\x0b\x32\x14.hnd.HttpStatusError\x12\x12\n\nerror_type\x18\x05 \x01(\t:V\n\x13http_server_options\x12\x1f.google.protobuf.ServiceOptions\x18\xd2\x86\x03 \x01(\x0b\x32\x16.hnd.HttpServerOptions:H\n\x0chttp_options\x12\x1e.google.protobuf.MethodOptions\x18\xd1\x86\x03 \x01(\x0b\x32\x10.hnd.HttpOptionsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


HTTP_SERVER_OPTIONS_FIELD_NUMBER = 50002
http_server_options = _descriptor.FieldDescriptor(
  name='http_server_options', full_name='hnd.http_server_options', index=0,
  number=50002, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
HTTP_OPTIONS_FIELD_NUMBER = 50001
http_options = _descriptor.FieldDescriptor(
  name='http_options', full_name='hnd.http_options', index=1,
  number=50001, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_HTTPSERVEROPTIONS = _descriptor.Descriptor(
  name='HttpServerOptions',
  full_name='hnd.HttpServerOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isHttpServer', full_name='hnd.HttpServerOptions.isHttpServer', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='hnd.HttpServerOptions.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=111,
)


_HTTPSTATUSERROR = _descriptor.Descriptor(
  name='HttpStatusError',
  full_name='hnd.HttpStatusError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='hnd.HttpStatusError.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='hnd.HttpStatusError.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=158,
)


_HTTPOPTIONS = _descriptor.Descriptor(
  name='HttpOptions',
  full_name='hnd.HttpOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='hnd.HttpOptions.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='hnd.HttpOptions.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='impl', full_name='hnd.HttpOptions.impl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_overrides', full_name='hnd.HttpOptions.error_overrides', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_type', full_name='hnd.HttpOptions.error_type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=284,
)

_HTTPOPTIONS.fields_by_name['error_overrides'].message_type = _HTTPSTATUSERROR
DESCRIPTOR.message_types_by_name['HttpServerOptions'] = _HTTPSERVEROPTIONS
DESCRIPTOR.message_types_by_name['HttpStatusError'] = _HTTPSTATUSERROR
DESCRIPTOR.message_types_by_name['HttpOptions'] = _HTTPOPTIONS
DESCRIPTOR.extensions_by_name['http_server_options'] = http_server_options
DESCRIPTOR.extensions_by_name['http_options'] = http_options
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HttpServerOptions = _reflection.GeneratedProtocolMessageType('HttpServerOptions', (_message.Message,), dict(
  DESCRIPTOR = _HTTPSERVEROPTIONS,
  __module__ = 'hnd.ext_pb2'
  # @@protoc_insertion_point(class_scope:hnd.HttpServerOptions)
  ))
_sym_db.RegisterMessage(HttpServerOptions)

HttpStatusError = _reflection.GeneratedProtocolMessageType('HttpStatusError', (_message.Message,), dict(
  DESCRIPTOR = _HTTPSTATUSERROR,
  __module__ = 'hnd.ext_pb2'
  # @@protoc_insertion_point(class_scope:hnd.HttpStatusError)
  ))
_sym_db.RegisterMessage(HttpStatusError)

HttpOptions = _reflection.GeneratedProtocolMessageType('HttpOptions', (_message.Message,), dict(
  DESCRIPTOR = _HTTPOPTIONS,
  __module__ = 'hnd.ext_pb2'
  # @@protoc_insertion_point(class_scope:hnd.HttpOptions)
  ))
_sym_db.RegisterMessage(HttpOptions)

http_server_options.message_type = _HTTPSERVEROPTIONS
google_dot_protobuf_dot_descriptor__pb2.ServiceOptions.RegisterExtension(http_server_options)
http_options.message_type = _HTTPOPTIONS
google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(http_options)

# @@protoc_insertion_point(module_scope)
