# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: https_test/ext.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='https_test/ext.proto',
  package='https_test',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14https_test/ext.proto\x12\nhttps_test\x1a google/protobuf/descriptor.proto\"7\n\x11HttpServerOptions\x12\x14\n\x0cisHttpServer\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\"-\n\x0fHttpStatusError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\"\x83\x01\n\x0bHttpOptions\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0c\n\x04impl\x18\x03 \x01(\t\x12\x34\n\x0f\x65rror_overrides\x18\x04 \x03(\x0b\x32\x1b.https_test.HttpStatusError\x12\x12\n\nerror_type\x18\x05 \x01(\t:]\n\x13http_server_options\x12\x1f.google.protobuf.ServiceOptions\x18\xd2\x86\x03 \x01(\x0b\x32\x1d.https_test.HttpServerOptions:O\n\x0chttp_options\x12\x1e.google.protobuf.MethodOptions\x18\xd1\x86\x03 \x01(\x0b\x32\x17.https_test.HttpOptionsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


HTTP_SERVER_OPTIONS_FIELD_NUMBER = 50002
http_server_options = _descriptor.FieldDescriptor(
  name='http_server_options', full_name='https_test.http_server_options', index=0,
  number=50002, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
HTTP_OPTIONS_FIELD_NUMBER = 50001
http_options = _descriptor.FieldDescriptor(
  name='http_options', full_name='https_test.http_options', index=1,
  number=50001, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_HTTPSERVEROPTIONS = _descriptor.Descriptor(
  name='HttpServerOptions',
  full_name='https_test.HttpServerOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isHttpServer', full_name='https_test.HttpServerOptions.isHttpServer', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='https_test.HttpServerOptions.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=125,
)


_HTTPSTATUSERROR = _descriptor.Descriptor(
  name='HttpStatusError',
  full_name='https_test.HttpStatusError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='https_test.HttpStatusError.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='https_test.HttpStatusError.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=172,
)


_HTTPOPTIONS = _descriptor.Descriptor(
  name='HttpOptions',
  full_name='https_test.HttpOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='https_test.HttpOptions.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='https_test.HttpOptions.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='impl', full_name='https_test.HttpOptions.impl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_overrides', full_name='https_test.HttpOptions.error_overrides', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_type', full_name='https_test.HttpOptions.error_type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=306,
)

_HTTPOPTIONS.fields_by_name['error_overrides'].message_type = _HTTPSTATUSERROR
DESCRIPTOR.message_types_by_name['HttpServerOptions'] = _HTTPSERVEROPTIONS
DESCRIPTOR.message_types_by_name['HttpStatusError'] = _HTTPSTATUSERROR
DESCRIPTOR.message_types_by_name['HttpOptions'] = _HTTPOPTIONS
DESCRIPTOR.extensions_by_name['http_server_options'] = http_server_options
DESCRIPTOR.extensions_by_name['http_options'] = http_options
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HttpServerOptions = _reflection.GeneratedProtocolMessageType('HttpServerOptions', (_message.Message,), dict(
  DESCRIPTOR = _HTTPSERVEROPTIONS,
  __module__ = 'https_test.ext_pb2'
  # @@protoc_insertion_point(class_scope:https_test.HttpServerOptions)
  ))
_sym_db.RegisterMessage(HttpServerOptions)

HttpStatusError = _reflection.GeneratedProtocolMessageType('HttpStatusError', (_message.Message,), dict(
  DESCRIPTOR = _HTTPSTATUSERROR,
  __module__ = 'https_test.ext_pb2'
  # @@protoc_insertion_point(class_scope:https_test.HttpStatusError)
  ))
_sym_db.RegisterMessage(HttpStatusError)

HttpOptions = _reflection.GeneratedProtocolMessageType('HttpOptions', (_message.Message,), dict(
  DESCRIPTOR = _HTTPOPTIONS,
  __module__ = 'https_test.ext_pb2'
  # @@protoc_insertion_point(class_scope:https_test.HttpOptions)
  ))
_sym_db.RegisterMessage(HttpOptions)

http_server_options.message_type = _HTTPSERVEROPTIONS
google_dot_protobuf_dot_descriptor__pb2.ServiceOptions.RegisterExtension(http_server_options)
http_options.message_type = _HTTPOPTIONS
google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(http_options)

# @@protoc_insertion_point(module_scope)
